# Generated by Django 4.2.1 on 2023-05-27 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('P', 'Parent'), ('C', 'Children')], max_length=1)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='api.family')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Undefined')], max_length=1)),
                ('date_birth', models.DateField()),
                ('date_death', models.DateField(blank=True, null=True)),
                ('families', models.ManyToManyField(through='api.FamilyPerson', to='api.family')),
            ],
        ),
        migrations.AddField(
            model_name='familyperson',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='api.person'),
        ),
        migrations.AddField(
            model_name='family',
            name='persons',
            field=models.ManyToManyField(through='api.FamilyPerson', to='api.person'),
        ),
    ]
