# Generated by Django 4.2.1 on 2023-05-21 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentsChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='api.people')),
                ('first_parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_parent', to='api.people')),
                ('second_parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_parent', to='api.people')),
            ],
        ),
    ]
