# Generated by Django 4.2.1 on 2023-05-22 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_family'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parentschild',
            old_name='first_parent_id',
            new_name='parent_id',
        ),
        migrations.RemoveField(
            model_name='parentschild',
            name='second_parent_id',
        ),
    ]
